# Generated by Django 4.1.5 on 2023-01-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santosblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_published',
            new_name='time_published',
        ),
    ]
